### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by mshuaibii** [markpwoodward/active_osl#4]
Hi Mark!

Interesting work! I'm currently exploring online active-learning schemes for a time-series  regression based problem. Your paper focuses on classification based problems. Have you explored regression problems? Is your code suited for such applications? Thanks!

**Comment by markpwoodward** [comment]
@mshuaibii Thank you for your interest! I have only explored classification problems, and thus a DRQN style network was a good fit. With classification, the "request label" action just becomes another discrete action to estimate the Q value of. With regression, you now have a discrete choice between predicting and requesting, and, if predicting, you need to output a continuous value(s). For the regression case, you probably want to introduce a policy, likely with two heads (one for the binary "request value" action, and one that predicts value) . Tons of algorithms to pick from in the policy gradient space. You'll likely want an actor-critic method.

The training setup should be the same. i.e. the construction of episodes and serial presentation of examples within the episode. Of course the model and loss would change. The code could be modified for this case, but it was written with "graph mode" execution in mind, and you might want to train in eager mode...
